name: "DashLord init action"
description: "Parse dashlord config files"
outputs:
  urls:
    description: List of urls to scan as plain text
    value: ${{ steps.init.outputs.urls }}
  urls_json:
    description: List of urls to scan as json
    value: ${{ steps.init.outputs.urls_json }}
  json:
    description: Full dashlord.yaml config
    value: ${{ steps.init.outputs.json }}
runs:
  using: 'node12'
  main: 'dist/index.js'